package project1;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
/**
 *
 * @author mbera
 */
public class Test extends javax.swing.JFrame {

    LinkedList valuesList = new LinkedList();
    int[][] values = {{2, 0}, {2, 3}, {4, 1}, {2, 2}, {4, 4}, {2, 1}, {4, 4}, {8, 0}, {8, 0}, {32, 1},
    {2, 2}, {64, 2}, {16, 3}, {64, 1}, {32, 2}, {16, 0}, {16, 4}, {32, 2}, {64, 1}, {8, 3}, {4, 3},
    {2, 3}, {2, 3}, {2, 1}, {64, 2}, {32, 2}, {16, 2}, {8, 2}, {8, 2}, {4, 1}, {8, 1}};
    int[][] valuesMatrix = new int[7][5];
    int count = 0;

    /**
     * Creates new form main
     */
    public Test() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.setColor(Color.BLACK);        
        for (int i = 0; i < valuesMatrix.length; i++) {
            for (int j = 0; j < valuesMatrix[i].length; j++) {
                g.drawRect(j * 50 + 45, i * 50 + 45, 50, 50);
                if (valuesMatrix[i][j] != 0) {                    
                    g.setColor(getColor(valuesMatrix[i][j]));
                    g.setFont(new Font("Serif", Font.BOLD, 20));
                    g.drawString(valuesMatrix[i][j] + "", j * 52 + 60, i * 50 + 80);
                    g.setColor(Color.BLACK);                    
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 217, 230));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 217, 230));
        jPanel1.setForeground(new java.awt.Color(204, 217, 230));
        jPanel1.setMinimumSize(new java.awt.Dimension(67, 34));
        jPanel1.setPreferredSize(new java.awt.Dimension(67, 34));
        jPanel1.setRequestFocusEnabled(false);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Game started. Good luck.");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (count > 30) {
            jLabel1.setText("GAME OVER.");
            jButton1.setEnabled(false);
        } else {
            Node<Integer> node = new Node<>(values[count][0], values[count][1]);
            valuesList.add(node);
            toMatris(valuesList);
            repaint();
            count++;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        valuesList = new LinkedList();
        valuesMatrix = new int[7][5];
        repaint();
        count = 0;
        jLabel1.setText("Good Luck.");
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public Color getColor(int value) { // This method takes an integer parameter value and returns a color corresponding to that value.
        switch (value) {
        case 2:
            return new Color(119, 158, 203); // light blue
        case 4:
            return new Color(128, 128, 128); // light gray
        case 8:
            return new Color(221, 160, 221); // lavender
        case 16:
            return new Color(255, 215, 0); // gold
        case 32:
            return new Color(238, 130, 238); // violet
        case 64:
            return new Color(255, 0, 0); // red
        case 128:
            return new Color(255, 255, 153); // light yellow
        case 256:
            return new Color(128, 128, 128); // gray
        default:
            throw new AssertionError();
    }
    }

    public void toMatris(LinkedList list) {
        valuesMatrix = new int[7][5];
        Node rightLeft = list.head;
        int rowNumber = 6;
        while (rightLeft != null) {
            Node upDown = rightLeft;
            rowNumber = 6;
            while (upDown != null) {
                valuesMatrix[rowNumber][upDown.column] = upDown.data;
                upDown = upDown.up;
                rowNumber--;
            }
            rightLeft = rightLeft.next;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
